spring.application.name: my-rag-example

spring:
  ai:
    mcp:
      server:
        protocol: streamable
        stdio: false
        type: sync

    # https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html
    ollama:
      base-url: http://localhost:11434
      chat.options.model: gpt-oss
      embedding:
        options:
          model: nomic-embed-text
  mongodb:
    uri: mongodb+srv://${DB_USERNAME}:${DB_PASSWORD}@cluster0.zcamfyk.mongodb.net/?appName=Cluster0
    database: my-rag